"""
Base Strategy Classes

Defines the interface and common components for all trading strategies.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any
import pandas as pd


class SignalType(str, Enum):
    """Trading signal types"""
    STRONG_BUY = "strong_buy"
    BUY = "buy"
    HOLD = "hold"
    SELL = "sell"
    STRONG_SELL = "strong_sell"


@dataclass
class StrategySignal:
    """A trading signal generated by a strategy"""
    symbol: str
    signal_type: SignalType
    strength: float  # 0 to 1
    price: float
    timestamp: datetime
    reason: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Position:
    """A position in a portfolio"""
    symbol: str
    quantity: float
    entry_price: float
    entry_date: datetime
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    unrealized_pnl_pct: float = 0.0

    def update_price(self, price: float):
        """Update current price and PnL"""
        self.current_price = price
        self.unrealized_pnl = (price - self.entry_price) * self.quantity
        self.unrealized_pnl_pct = (price - self.entry_price) / self.entry_price * 100


@dataclass
class Trade:
    """A completed trade"""
    symbol: str
    side: str  # "buy" or "sell"
    quantity: float
    price: float
    timestamp: datetime
    commission: float = 0.0
    strategy: str = ""
    signal_reason: str = ""


@dataclass
class StrategyResult:
    """Results from running a strategy"""
    strategy_name: str
    symbols: List[str]
    signals: List[StrategySignal]
    summary: Dict[str, Any]
    timestamp: datetime = field(default_factory=datetime.now)


class Strategy(ABC):
    """
    Base class for all trading strategies.

    A strategy analyzes market data and generates trading signals.

    Usage:
        class MyStrategy(Strategy):
            def analyze(self, data, symbols):
                # Your analysis logic
                return StrategyResult(...)
    """

    name: str = "base_strategy"
    description: str = ""

    def __init__(self, params: Optional[Dict[str, Any]] = None):
        self.params = params or {}

    @abstractmethod
    def analyze(
        self,
        data: Dict[str, pd.DataFrame],
        symbols: List[str],
    ) -> StrategyResult:
        """
        Analyze market data and generate signals.

        Args:
            data: Dict mapping symbol to OHLCV DataFrame
            symbols: List of symbols to analyze

        Returns:
            StrategyResult with signals and analysis
        """
        pass

    def validate_data(self, data: Dict[str, pd.DataFrame], min_rows: int = 20) -> bool:
        """Validate that data has sufficient history"""
        for symbol, df in data.items():
            if df is None or len(df) < min_rows:
                return False
        return True

    def get_signal_type(self, score: float) -> SignalType:
        """Convert a score (-1 to 1) to signal type"""
        if score >= 0.6:
            return SignalType.STRONG_BUY
        elif score >= 0.2:
            return SignalType.BUY
        elif score <= -0.6:
            return SignalType.STRONG_SELL
        elif score <= -0.2:
            return SignalType.SELL
        return SignalType.HOLD
